"""extend llm_usage_logs with metadata fields

Revision ID: 1e923c533402
Revises: 0e4744b6e00d
Create Date: 2026-03-17 15:23:48.239951

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1e923c533402'
down_revision: Union[str, Sequence[str], None] = '0e4744b6e00d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('llm_usage_logs', sa.Column('org_id', sa.String(length=36), nullable=True))
    op.add_column('llm_usage_logs', sa.Column('key_source', sa.String(length=16), nullable=True))
    op.add_column('llm_usage_logs', sa.Column('request_path', sa.String(length=256), nullable=True))
    op.add_column('llm_usage_logs', sa.Column('is_stream', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('llm_usage_logs', sa.Column('status_code', sa.Integer(), nullable=True))
    op.add_column('llm_usage_logs', sa.Column('latency_ms', sa.Integer(), nullable=True))
    op.add_column('llm_usage_logs', sa.Column('error_message', sa.String(length=512), nullable=True))
    op.add_column('llm_usage_logs', sa.Column('request_body', sa.Text(), nullable=True))
    op.add_column('llm_usage_logs', sa.Column('response_body', sa.Text(), nullable=True))
    op.alter_column('llm_usage_logs', 'model',
               existing_type=sa.VARCHAR(length=64),
               type_=sa.String(length=128),
               existing_nullable=True)
    op.create_index(op.f('ix_llm_usage_logs_instance_id'), 'llm_usage_logs', ['instance_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_llm_usage_logs_instance_id'), table_name='llm_usage_logs')
    op.alter_column('llm_usage_logs', 'model',
               existing_type=sa.String(length=128),
               type_=sa.VARCHAR(length=64),
               existing_nullable=True)
    op.drop_column('llm_usage_logs', 'response_body')
    op.drop_column('llm_usage_logs', 'request_body')
    op.drop_column('llm_usage_logs', 'error_message')
    op.drop_column('llm_usage_logs', 'latency_ms')
    op.drop_column('llm_usage_logs', 'status_code')
    op.drop_column('llm_usage_logs', 'is_stream')
    op.drop_column('llm_usage_logs', 'request_path')
    op.drop_column('llm_usage_logs', 'key_source')
    op.drop_column('llm_usage_logs', 'org_id')
    # ### end Alembic commands ###
